# Custom Functions -------------------------------------------------------
.custom_functions: &custom_functions |
  function replace_files_variables() {
    VAR_LIST=(
      "DB_HOST"
      "DB_PORT"
      "DB_DATABASE"
      "DB_USERNAME"
      "DB_PASSWORD"
    )

    for VAR_ITEM in "${VAR_LIST[@]}"; do
      ENV_VAR="${VAR_ITEM}";
      sed -i 's/'"_${VAR_ITEM}_"'/'"${!ENV_VAR}"'/g' docker/.env;
    done
  }
# END Custom Functions -------------------------------------------------------

cache:
  paths:
    - .m2/repository

stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3-openjdk-8
  tags:
    - aws
  artifacts:
    expire_in: 1 week
    paths:
      - target/candidate-case-api.jar
  script:
    - mvn clean package -Dspring.profiles.active=test

deploy-stg:
  stage: deploy
  dependencies:
    - build
  image: carloscesargsf/docker-openssh-client
  tags:
    - aws
  environment:
    name: staging
    url: https://candidate-case-stg.carloscesargsf.com.br/swagger-ui.html
  before_script:
    - *custom_functions
  script:
    - replace_files_variables
    - cat docker/.env
    - ls -liah target/
    - ls -liah
    - scp target/candidate-case-api.jar docker/Dockerfile docker/.env ec2-user@172.31.41.231
    - ssh ec2-user@172.31.41.231 /bin/bash <<'EOT'
    - docker system prune -f
    - docker build -t candidate-case-api .
    - docker stop candidate-case-api
    - docker rm candidate-case-api
    #- docker run -d --restart unless-stopped --name=candidate-case-api -p80:8080 --env-file=.env candidate-case-api
    - docker images
    - EOT
